# Generated by Django 3.1.3 on 2020-11-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='phone',
        ),
    ]
