# Generated by Django 3.1.3 on 2021-01-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210112_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image1',
            field=models.ImageField(default='categories/defaultimage.jpg', upload_to='categories/%Y/%m'),
        ),
    ]
