# Generated by Django 3.1.3 on 2021-01-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='technical_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
